name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.14
    steps:
      - name: log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:17-alpine3.14
        with:
          entrypoint: '/bin/echo'
          args: 'Hello, World!'
      - name: Log node version
        uses: docker://node:17-alpine3.14
        with:
          entrypoint: '/usr/local/bin/node'
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        run: |
          chmod +x ./scripts.sh
          ./scripts.sh strhoho
  # node-docker:
  #   runs-on: ubuntu-latest
  #   services:
  #     app:
  #       image: cuncis1st/simple-docker-nodejs-api_app
  #       ports: 
  #         - 3001:3000
  #     mongo:
  #       image: mongo
  #       ports: 
  #         - 27017:27017
  #   steps:
  #     - name: check location curl
  #       run: which curl
  #     # - name: Post User
  #     #   run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "lord", "address": "hell"}'''
  #     - name: Get Users
  #       run: curl http://localhost:3001/api/users